# This file defines the min/max field values of Transaction message

ORDER_MIN_PRICE = 0.00001
ORDER_MIN_SIZE = 0.00001

SE_MIN_VALUE = 0
SE_MAX_VALUE = 4

ORDTYPE_MIN_VALUE = 0
ORDTYPE_MAX_VALUE = 17

MSGTYPE_MIN_VALUE = 0
MSGTYPE_MAX_VALUE = 22

MAX_LAYERS = 10

LOGON_TYPE_LOGON = 1
LOGON_TYPE_LOGOUT = 2

TRANS_ATTR_Y = "Y"
TRANS_ATTR_N = "N"
TRANS_ATTR_LEN = 12
