# This file defines the min/max field values of Transaction message

ORDER_MIN_PRICE = 0.00001
ORDER_MIN_SIZE = 0.00001

SE_MIN_VALUE = 0
SE_MAX_VALUE = 4

ORDTYPE_MIN_VALUE = 0
ORDTYPE_MAX_VALUE = 17

MSGTYPE_MIN_VALUE = 0
MSGTYPE_MAX_VALUE = 22

MAX_LAYERS = 10

LOGON_TYPE_LOGON = 1
LOGON_TYPE_LOGOUT = 2

TRANS_ATTR_RESERVED = 0
TRANS_ATTR_HIDDEN = 1
TRANS_ATTR_DISPLY = 2
TRANS_ATTR_SIZEINCREMENT = 3
TRANS_ATTR_POST = 4
TRANS_ATTR_PRICEINCREMENT = 5
TRANS_ATTR_OFFSET = 6
TRANS_ATTR_STOP_MKT = 7
TRANS_ATTR_STOP_LMT = 8
TRANS_ATTR_PEG = 9
TRANS_ATTR_TSL = 10
TRANS_ATTR_TSM = 11

TRANS_ATTR_Y = "Y"
TRANS_ATTR_N = "N"
TRANS_ATTR_LEN = 12
